// Chapter 7. Gradient descent live — in pure Swift.
//
// We train the simplest model y = w*x + b to fit points generated by the rule
// y = 2x + 1. The model doesn't know this rule — it finds w and b itself, stepping
// down the slope of error. The whole loop is visible: forward -> loss -> backward -> update.
//
// Run:
//     swift ch07_gradient_descent.swift

import Foundation

// Data generated by the rule y = 2x + 1 (the model does NOT know it).
let data: [(Double, Double)] = [(1, 3), (2, 5), (3, 7), (4, 9)]

var w = 0.0   // starting "random" (here zero) parameters
var b = 0.0
let lr = 0.01 // learning rate — the size of the step down the slope
let n = Double(data.count)

func f(_ x: Double, _ d: Int) -> String { String(format: "%.\(d)f", x) }

for epoch in 1...1000 {
    var gradW = 0.0, gradB = 0.0, loss = 0.0
    for (x, y) in data {
        let pred = w * x + b      // FORWARD: prediction
        let err = pred - y        // error on the example
        loss += err * err         // LOSS: squared error (MSE)
        gradW += 2 * err * x      // BACKWARD: d(err^2)/dw
        gradB += 2 * err          //           d(err^2)/db
    }
    // UPDATE: a step against the averaged gradient
    w -= lr * gradW / n
    b -= lr * gradB / n
    if epoch % 200 == 0 {
        print("epoch \(epoch): loss=\(f(loss / n, 4))  w=\(f(w, 3))  b=\(f(b, 3))")
    }
}

print("\nResult: the model learned y = \(f(w, 3))*x + \(f(b, 3))  (truth: 2*x + 1)")
